djangostripe/djangostripe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payments.urls')),
]

djangostripe/payments/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('detail/<id>/', ProductDetailView.as_view(), name='detail'),
    path('success/', PaymentSuccessView.as_view(), name='success'),
    path('failed/', PaymentFailedView.as_view(), name='failed'),
    path('history/', OrderHistoryListView.as_view(), name='history'),

    path('api/checkout-session/<id>/', create_checkout_session, name='api_checkout_session'),
]

shootingrange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from mainapp.views import (home_screen_view, zarzadzanie, BlogMainView, Payment, payment_redirect, post_payment,  BlogUserView, BlogUserUpdateAdminView, PostDetailView, PostCreateView, ForumListView, ForumTopicCreateView, ForumPostCreateView, ForumPostDetailView, blog_registration)
from zawody.views import (ZawodyCreateView, ZawodyDynamicCreateView, SedziaCreateView, sedzia_create, sedzia_dynamic_create, SedziaDynamicCreateView,  SedziaListView, SedziaDynamicListView, SedziaDeleteView, SedziaDynamicDeleteView, ZawodyListView, ZawodyDynamicListView, ZawodyDeleteView, ZawodyDynamicDeleteView, StronaStartowaListView, ZawodyEditView, ZawodyDynamicEditView, TurniejArchiwalnyListView, ZawodyGrupaListView, ZawodyGrupaCreateView, ZawodyGrupaEditView, ZawodyGrupaDeleteView, druzyny_management, ZawodnicyDruzynyCreateView, DruzynaCreateView)
from account.views import (registration_form, registration_form_sedzia, registration_form_no_login, logout_view, login_view, login_info, AccountListView, AccountUpdateView, AccountUpdateViewPersonal, AccountDeleteView, PasswordResetViewNew, PasswordResetDoneViewNew, PasswordResetConfirmViewNew, PasswordResetCompleteViewNew, SedziaUpdateView, RodoUpdateView)
from wyniki.views import (wyniki_edycja, wyniki_dynamic_edycja,  wyniki, wyniki_general, wyniki_druzynowe, exportexcel, exportexceldynamic, exportexcelgeneralka, export_psv_wyniki_general,  WynikUpdateView, WynikDynamicUpdateView, not_authorized, RejestracjaNaZawodyView,  RejestracjaNaZawodyDynamicView, KonkurencjaDeleteView, KonkurencjaDynamicDeleteView, TurniejListView, TurniejDeleteView, TurniejEditView, TurniejCreateView, OplataListView, OplataDynamicListView, OplataUpdateView, OplataDynamicUpdateView, UczestnikDeleteView, BronAmunicjaListView, rejestracja_choose)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('json/', view_accounts, name='view_accounts'),
    # path('start/', StronaStartowaListView.as_view(), name="start"),
    path('start/', StronaStartowaListView.as_view(), name="start"),
    path('', BlogMainView.as_view(), name="BlogMainView"),
    path('forum/', ForumListView.as_view(), name="ForumListView"),
    path('blog_users/', BlogUserView.as_view(), name="BlogUserView"),
    # path('payment/', Payment.as_view(), name="Payment"),
    path('payment/', Payment.as_view(), name="Payment"),
    path('payment_redirect/', payment_redirect, name="payment_redirect"),
    path('post_payment/', post_payment, name="post_payment"),
    # path('secure.przelewy24.pl/trnRequest/<TOKEN:str>/', PaymentRedirect.as_view(), name="payment_redirect"),
    path('forum_topic_create/', ForumTopicCreateView.as_view(), name="ForumTopicCreateView"),
    path('forum_post_create/', ForumPostCreateView.as_view(), name="ForumPostCreateView"),
    path('forum_post_detail/<slug:slug>/', ForumPostDetailView.as_view(), name="ForumPostDetailView"),
    path('blog_user_update/<int:pk>/', BlogUserUpdateAdminView.as_view(), name="BlogUserUpdateAdminView"),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/blog_login.html'), name="LoginView"),
    path('logout/', auth_views.LogoutView.as_view(template_name='mainapp/blog_logout.html'), name="LogoutView"),
    path('post/<slug:slug>/', PostDetailView.as_view(), name="PostDetailView"),
    path('post_create/', PostCreateView.as_view(), name="PostCreateView"),
    path('blog_registration/', blog_registration, name="blog_registration"),
    path('archive', TurniejArchiwalnyListView.as_view(), name="start_archive"),
    path('<int:pk>/', home_screen_view, name="home"),
    path('<int:pk>/register/', registration_form, name="register"),
    path('<int:pk>/zarzadzanie/', zarzadzanie, name="zarzadzanie"),
    path('<int:pk>/register_sedzia/', registration_form_sedzia, name="register_sedzia"),
    path('<int:pk>/register_no_login/', registration_form_no_login, name="register_no_login"),
    path('users/<int:pk>/', AccountListView.as_view(), name="users"),
    path('logout/<int:pk>', logout_view, name="logout"),
    path('login/<int:pk>/', login_view, name="login"),
    path('login/', login_info, name="login_info"),
    path('<int:pk>/wyniki_edycja/', wyniki_edycja, name="wyniki_edycja"),
    path('<int:pk>/wyniki_dynamic_edycja/', wyniki_dynamic_edycja, name="wyniki_dynamic_edycja"),
    path('wyniki/<int:pk>/', wyniki, name="wyniki"),
    path('wybierz_zawody/<int:pk>/', rejestracja_choose, name="rejestracja_choose"),
    path('druzyny/<int:pk>/', druzyny_management, name="druzyny_management"),
    path('druzyny_add/<int:pk>/<slug:druzyna_slug>', ZawodnicyDruzynyCreateView.as_view(), name="zawodnicy_druzyny_create_view"),
    path('druzyna_create/<int:pk>', DruzynaCreateView.as_view(), name="druzyna_create"),

    path('wyniki_general/<int:pk>/', wyniki_general, name="wyniki_general"),
    path('wyniki_druzynowe/<int:pk>/', wyniki_druzynowe, name="wyniki_druzynowe"),
    path('rejestracja_na_zawody/<int:pk>/', RejestracjaNaZawodyView.as_view(), name="rejestracja_na_zawody"),
    path('rejestracja_na_zawody_dynamic/<int:pk>/', RejestracjaNaZawodyDynamicView.as_view(), name="rejestracja_na_zawody_dynamic"),
    path('<int:pk>/wyniki_edit/<int:pk_turniej>/', WynikUpdateView.as_view(), name="wyniki_edit"),
    path('<int:pk>/wyniki_dynamic_edit/<int:pk_turniej>/', WynikDynamicUpdateView.as_view(), name="wyniki_dynamic_edit"),
    path('<int:pk>/account_edit/<int:pk_turniej>/', AccountUpdateView.as_view(), name="account_edit"),
    path('<int:pk>/rodo_edit/<int:pk_turniej>/', RodoUpdateView.as_view(), name="rodo_edit"),
    path('<int:pk>/account_edit_personal/<int:pk_turniej>/', AccountUpdateViewPersonal.as_view(), name="account_edit_personal"),
    path('<int:pk>/sedzia_edit/<int:pk_turniej>/', SedziaUpdateView.as_view(), name="sedzia_edit"),
    path('<int:pk>/account_delete/<int:pk_turniej>/',AccountDeleteView.as_view(), name="account_delete"),
    path('<int:pk>/konkurencja_delete/<int:pk_turniej>',KonkurencjaDeleteView.as_view(), name="konkurencja_delete"),
    path('<int:pk>/konkurencja_dynamic_delete/<int:pk_turniej>',KonkurencjaDynamicDeleteView.as_view(), name="konkurencja_dynamic_delete"),
    path('<int:pk>/exportexcel', exportexcel, name="exportexcel"),
    path('<int:pk>/exportexceldynamic', exportexceldynamic, name="exportexceldynamic"),
    path('<int:pk>/exportexcelgeneralka', exportexcelgeneralka, name="exportexcelgeneralka"),
    path('<int:pk>/export_psv_wyniki_general', export_psv_wyniki_general, name="export_psv_wyniki_general"),
    path('dodaj_zawody/<int:pk>/', ZawodyCreateView.as_view(), name="dodaj_zawody"),
    path('dodaj_zawody_dynamic/<int:pk>/', ZawodyDynamicCreateView.as_view(), name="dodaj_zawody_dynamic"),
    # path('<int:pk>/dodaj_sedziego/', SedziaCreateView.as_view(), name="dodaj_sedziego"),
    path('<int:pk>/dodaj_sedziego/', sedzia_create, name="dodaj_sedziego"),
    # path('<int:pk>/dodaj_sedziego_dynamic/', SedziaDynamicCreateView.as_view(), name="dodaj_sedziego_dynamic"),
    path('<int:pk>/dodaj_sedziego_dynamic/', sedzia_dynamic_create, name="dodaj_sedziego_dynamic"),
    path('<int:pk>/sedzia_lista/', SedziaListView.as_view(), name="sedzia_lista"),
    path('<int:pk>/sedzia_dynamic_lista/', SedziaDynamicListView.as_view(), name="sedzia_dynamic_lista"),
    path('zawody_lista/<int:pk>', ZawodyListView.as_view(), name="zawody_lista"),
    path('zawody_dynamic_lista/<int:pk>', ZawodyDynamicListView.as_view(), name="zawody_dynamic_lista"),
    path('<int:pk>/zawody_delete/<int:pk_turniej>', ZawodyDeleteView.as_view(), name="zawody_delete"),
    path('<int:pk>/zawody_dynamic_delete/<int:pk_turniej>', ZawodyDynamicDeleteView.as_view(), name="zawody_dynamic_delete"),
    path('<int:pk>/delete/<int:pk_turniej>',SedziaDeleteView.as_view(), name="sedzia_delete"),
    path('<int:pk>/sedzia_dynamic_delete/<int:pk_turniej>',SedziaDynamicDeleteView.as_view(), name="sedzia_dynamic_delete"),
    path('not_authorized/',not_authorized, name="not_authorized"),
    path('<int:pk>/turnieje/',TurniejListView.as_view(), name="turnieje"),
    path('<int:pk>/turniej_edit/<int:pk_turniej>/', TurniejEditView.as_view(), name="turniej_edit"),
    path('<int:pk>/zawody_edit/<int:pk_turniej>/', ZawodyEditView.as_view(), name="zawody_edit"),
    path('<int:pk>/zawody_dynamic_edit/<int:pk_turniej>/', ZawodyDynamicEditView.as_view(), name="zawody_dynamic_edit"),
    path('<int:pk>/turniej_delete/<int:pk_turniej>/', TurniejDeleteView.as_view(), name="turniej_delete"),
    path('<int:pk>/turniej_add/', TurniejCreateView.as_view(), name="turniej_add"),
    path('oplata/<int:pk>/', OplataListView.as_view(), name="oplata_list"),
    path('oplata_dynamic/<int:pk>/', OplataDynamicListView.as_view(), name="oplata_dynamic_list"),
    path('bron_amunicja_list/<int:pk>/', BronAmunicjaListView.as_view(), name="bron_amunicja_list"),
    # path('<int:pk>/oplata_update/<int:pk_turniej>/', OplataUpdateView.as_view(), name="oplata_update"),
    path('<int:pk>/oplata_update/<int:pk_turniej>/', OplataUpdateView.as_view(), name="oplata_update"),
    path('<int:pk>/oplata_dynamic_update/<int:pk_turniej>/', OplataDynamicUpdateView.as_view(), name="oplata_dynamic_update"),
    path('<int:pk>/uczestnik_delete/<int:pk_turniej>/',UczestnikDeleteView.as_view(), name="uczestnik_delete"),
    path('zawody_grupa_lista/<int:pk>', ZawodyGrupaListView.as_view(), name="zawody_grupa_lista"),
    path('dodaj_grupe_zawodow/<int:pk>/', ZawodyGrupaCreateView.as_view(), name="dodaj_grupe_zawodow"),
    path('<int:pk>/zawody_grupa_edit/<int:pk_turniej>/', ZawodyGrupaEditView.as_view(), name="zawody_grupa_edit"),
    path('<int:pk>/zawody_grupa_delete/<int:pk_turniej>', ZawodyGrupaDeleteView.as_view(), name="zawody_grupa_delete"),
    path('tinymce/', include('tinymce.urls')),

djangostripe/payments/models.py
from django.db import models
from django.core import validators

# Create your models here.
class Product(models.Model):
    id = models.BigAutoField(
        primary_key=True
    )

    name = models.CharField(
        max_length=70,
        verbose_name='Product Name'
    )

    description = models.TextField(
        max_length=800,
        verbose_name='Description'
    )

    price = models.FloatField(
        verbose_name='Price',
        validators=[
            validators.MinValueValidator(50),
            validators.MaxValueValidator(100000)
        ]
    )

class OrderDetail(models.Model):

    id = models.BigAutoField(
        primary_key=True
    )

    # You can change as a Foreign Key to the user model
    customer_email = models.EmailField(
        verbose_name='Customer Email'
    )

    product = models.ForeignKey(
        to=Product,
        verbose_name='Product',
        on_delete=models.PROTECT
    )

    amount = models.IntegerField(
        verbose_name='Amount'
    )

    stripe_payment_intent = models.CharField(
        max_length=200
    )

    # This field can be changed as status
    has_paid = models.BooleanField(
        default=False,
        verbose_name='Payment Status'
    )

    created_on = models.DateTimeField(
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        auto_now_add=True
    )

mainapp/models.py
from django.db import models
from account.models import Account
from django.template.defaultfilters import slugify
from django.urls import reverse
from tinymce.models import HTMLField

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True, blank=True, verbose_name="Tytuł")
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(Account, on_delete= models.CASCADE,related_name='blog_posts', verbose_name="Autor")
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField(verbose_name="Treść")
    created_on = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d/', blank=True, verbose_name="Zdjęcie")

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
    	if not self.slug:
    		self.slug = slugify(self.title)
    	return super().save(*args, **kwargs)

    def get_absolute_url(self):
    	return reverse('PostDetailView', kwargs={'slug':self.slug})

    def comments(self):
    	return PostComment.objects.filter(post=self)


class PostComment(models.Model):
	post = models.ForeignKey(Post, on_delete= models.CASCADE)
	author = models.ForeignKey(Account, on_delete= models.CASCADE, verbose_name="Autor")
	updated_on = models.DateTimeField(auto_now= True)
	content = models.TextField(verbose_name="Treść")
	created_on = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created_on']

	def __str__(self):
		return 'Komentarz dodany przez {}'.format(self.author)



class ForumTopic(models.Model):
    topic = models.CharField(max_length=200, unique=True, blank=True, verbose_name='Temat')
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(Account, on_delete= models.CASCADE, verbose_name="Autor")

    def __str__(self):
        return self.topic


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.topic)
        return super().save(*args, **kwargs)

    def get_posts(self):
        return ForumPost.objects.filter(topic=self)

class ForumPost(models.Model):
    topic = models.ForeignKey(ForumTopic, on_delete= models.CASCADE, verbose_name='Temat')
    title = models.CharField(max_length=200, unique=True, blank=True, verbose_name='Tytuł')
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(Account, on_delete= models.CASCADE)
    content = HTMLField(verbose_name='Treść')
    created_on = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-created_on']


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def last_comment(self):
        return ForumComment.objects.filter(post=self).order_by('-created_on')


    def post_comments(self):
        return ForumComment.objects.filter(post=self).order_by('-created_on')



class ForumComment(models.Model):
    post = models.ForeignKey(ForumPost, on_delete= models.CASCADE, verbose_name='post')
    author = models.ForeignKey(Account, on_delete= models.CASCADE)
    content = HTMLField(verbose_name='Treść')
    created_on = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-created_on']


    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.title)
    #     return super().save(*args, **kwargs)


class LtsPayment(models.Model):
    user = models.ForeignKey(Account, on_delete= models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    year = models.IntegerField(default=2022)
    amount = models.IntegerField(default=0)
    result = models.CharField(null=True, max_length=200)
    token = models.CharField(max_length=200)
    sessionid = models.CharField(max_length=200)
    orderid = models.IntegerField(null=True)

    class Meta:
        ordering = ['-created_on']

mainapp/templates/mainapp/blog_logout.html
{% extends 'blog_base.html' %}
{% block content %}
{% load crispy_forms_tags %}

	<div class="content-section">
		<h2>Zostałeś wylogowany</h2>
		<div class="border-top pt-3">
			<small class="text-muted">
				<a class="ml-2" href="{% url 'LoginView' %}">Zaloguj się ponownie!</a>
			</small>
		</div>
	</div>
{% endblock %}

mainapp/templates/mainapp/blog_main_page.html
{% extends 'blog_base.html' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <div class="media-body container-fluid">
                <div class="article-metadata">
                    <a class="mr-2" >{{ post.author }}</a>
                    <small class="text-muted">{{ post.created_on }}</small>
                </div>
                	{% if post.image %}
                		<img class="img-fluid" src={{ post.image.url }}>
                	{% endif %}
                    <h2><a class="article-title" href="{% url 'PostDetailView' post.slug %}">{{ post.title }}</a></h2>
                    <p class="article-content">{{post.content}}</p>
                    <hr>               
                    <p class="article-content text-justify"><strong>Komentarze: </strong><span class="badge badge-dark ml-2">{{ post.comments.count }}</span></p>               
            </div>
        </article>
    {% endfor %}
    
{% endblock %}

mainapp/templates/mainapp/blog_register_xx.html
{% extends 'blog_base.html' %}
{% block content %}
{% load tailwind_filters %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Zarejestruj się</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Zarejestruj</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Masz już konto? <a class="ml-2" href="#">Zaloguj się!</a>
			</small>
		</div>
	</div>
{% endblock %}

mainapp/templates/mainapp/blog_user_update.html
{% extends 'blog_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Edytuj użytkownika</legend>
			<table>{{ form|crispy }}</table>
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Zapisz</button>
		</div>
	</form>
	
</div>

{% endblock %}

mainapp/templates/mainapp/forum.html
{% extends 'blog_base.html' %}



{% block menubar %}
    <a class="nav-item nav-link" href="{% url 'ForumTopicCreateView' %}">Dodaj temat na forum</a>
    <a class="nav-item nav-link" href="{% url 'ForumPostCreateView' %}">Dodaj post na forum</a>
{% endblock %}

{% block content %}

    <div class="container">




        {% for topic in topics %}
        <div class="subforum">

                <div class="subforum-title">
                    <h1>{{ topic.topic }}</h1>
                </div>

                {% for post in topic.get_posts%}

                    <div class="subforum-row">

                        <div class="subforum-description subforum-column">
                            <div class="col">
                                <h4><a href="{% url 'ForumPostDetailView' post.slug %}">{{ post.title }}</a></h4>
                                {% if post.last_comment.0 %}
                                <p>Ostatni wpis: {{ post.last_comment.0.author}} dnia: {{ post.last_comment.0.created_on|date:'Y-m-d H:i' }} </p>
                                {% endif %}

                            </div>
                        </div>

                    
                    </div>

                    {% endfor %}


        </div>
        {% endfor %}

        <!--More-->
        
        
        
    </div>

    <!-- Forum Info -->


    {% endblock content %}

mainapp/templates/mainapp/forum_post_detail.html
{% extends 'blog_base.html' %}



{% block menubar %}
    <a class="nav-item nav-link" href="{% url 'ForumTopicCreateView' %}">Dodaj temat na forum</a>
    <a class="nav-item nav-link" href="{% url 'ForumPostCreateView' %}">Dodaj post na forum</a>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="media-body container-fluid">
            <div class="article-metadata">
                <a class="mr-2" >{{ post.author }}</a>
                <small class="text-muted">{{ post.created_on }}</small>
             </div>

                <h2><a class="article-title" href="{% url 'PostDetailView' post.slug %}">{{ post.title }}</a></h2>
                <p class="article-content">{{post.content|safe}}</p>
                <hr>               

            </div>





        <div class="subforum">

                {% for comment in post.post_comments%}

                    <div class="subforum-row">

                        <div class="subforum-description subforum-column">
                            <div class="col">
                                <b>{{ comment.created_on|date:'Y-m-d H:i' }} {{ comment.author }} napisał:</b>
                                <p>{{ comment.content|safe }}</p>
                            </div>
                        </div>

                    
                    </div>

                    {% endfor %}


        </div>


<div class="">

<!-- ... -->

 <!-- List of comments -->


{% if user.is_authenticated %}
  <div class="row mt-5">
    <div class="col-lg-12">
      <h3>Zostaw komentarz</h3>
      <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
          <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary ml-2" type="submit">Dodaj</button>
      </form>
    </div>
  </div>
{% else %}
    <hr>
    <div class="row mt-5">
        <div class="col-lg-6">
            <strong>Zaloguj się aby dodać komentarz</strong>
        </div>
    </div>
{% endif %}

</div>
        
        
        
    </div>

    <!-- Forum Info -->


    {% endblock content %}

mainapp/templates/mainapp/forum_topic_create.html
{% extends 'blog_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Nowy temat</legend>
			{{ form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Dodaj</button>
		</div>
	</form>
	
</div>

{% endblock %}

mainapp/templates/mainapp/home.html
{% extends 'base.html' %}


{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Witaj</h1>
      {% if request.user.is_authenticated %}
      <p class="fs-5 text-muted">Teraz możesz zapisać się na zawody lub sprawdzić wyniki</p>
      {% else %}
      <p class="fs-5 text-muted">Zaloguj się lub zarejestruj żeby przejść dalej</p>
      {% endif %}
      <br>
      <p class="fs-5 text-muted mb-0">Jeśli napotkałeś problem napisz na:</p>
      <p class="fs-5 text-muted mt-0">pomoc.zawodylts@gmail.com</p>
    </div>



{% endblock content %}

mainapp/templates/mainapp/post_create.html
{% extends 'blog_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		<legend class="border-bottom mb-4">Nowy post</legend>
		{% csrf_token %}
		<table>{{ form.as_table }}</table>
		<button class="btn btn-outline-info" type="submit">Dodaj</button>

	</form>
	
</div>

{% endblock %}

mainapp/templates/mainapp/post_detail.html
{% extends 'blog_base.html' %}
{% block content %}
        <article class="media content-section">
            <div class="media-body container-fluid">
                <div class="article-metadata">
                    <a class="mr-2" >{{ post.author }}</a>
                    <small class="text-muted">{{ post.created_on }}</small>
                </div>
                    {% if post.image %}

                        <img class="img-fluid" src="{{ post.image.url }}">

                    {% endif %}
                    <h2><a class="article-title">{{ post.title }}</a></h2>
                    <p class="article-content">{{post.content}}</p>               
            




<div class="">

<!-- ... -->

 <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6">
      Komentarze
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
    <div class="col-lg-12 mt-2">
      <div class="card p-2">
        <div class="row">
          <div class="col-12">
            <strong>{{ comment.author }}</strong>
          </div>
          <div class="col-12">
            <p class="m-1 mt-3">{{ comment.content }}</p>
            <p class="text-right text-muted"><small>{{ comment.created_on }}</small></p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

{% if user.is_authenticated %}
  <div class="row mt-5">
    <div class="col-lg-12">
      <h3>Zostaw komentarz</h3>
      <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
          <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary ml-2" type="submit">Dodaj</button>
      </form>
    </div>
  </div>
{% else %}
    <hr>
    <div class="row mt-5">
        <div class="col-lg-6">
            <strong>Zaloguj się aby dodać komentarz</strong>
        </div>
    </div>
{% endif %}

</div>


</div>
        </article>
    
{% endblock %}